### PR TITLE
Snapshot api

### PR DESCRIPTION
**Pull request by baldwinSPC**
Hey RJ: 

Here's the pull request for our snapshot-api branch into your snapshot-api branch. We'll let you merge and then submit to the jClouds labs guys. Ping us over Skype or email if, upon review, we're doing something that doesn't seem right to you or the jClouds guy.  Please review this and let us know if there are any changes that need to be made. 

Thanks!
-matt

### CODE REVIEW

**Comment by devcsrj** [comment]
Hi @baldwinSPC , @jasminSPC  ! 

Thanks for submitting a PR! I made a few comments. Also could you resolve the conflicts so that it's in a mergeable state? This is so I can try running the live tests on my end. 

Also, syncing the git tree at least from [044511e](https://github.com/devcsrj/jclouds-labs/commit/044511e9701b60f078f59ef684d1db1759d72c93) would be appreciated. This is so I could review the changed files more closely. 

With that said, thanks for the great work!

**Comment by baldwinSPC** [comment]
Thanks RJ:

We'll take a look at these tomorrow morning.

Thanks.
-matt

**Comment by jasmingacic** [comment]
I've just made the changes.

**Comment by baldwinSPC** [comment]
Thanks Jasmin. RJ let us know if this clears everything up.

Tnx
-matt

I've just made the changes.

**Comment by devcsrj** [comment]
Hi @baldwinSPC , there are still merge conflicts on the code base. Could these be resolved first?

**Comment by jasmingacic** [comment]
I just resolved the conflicts, can you please let me know if it is ok. 

Thank you

**Comment by baldwinSPC** [comment]
I'm going to close and re-submit this to ensure the merge conflicts are corrected.

**Pull request closed without merging**
