### PR TITLE
NIC API

### PR DESCRIPTION
**Pull request by baldwinSPC**
Hey @devcsrj 

Here's our PR for NICs. Please let us know if there are any issues. GH indicates this PR can automatically merge into your nic-api branch. 

Thanks. 
-matt

### CODE REVIEW

**Comment by devcsrj** [comment]
Hi @baldwinSPC , @jasminSPC , as usual, thanks for the PR!

I see that in this PR, the NIC API commits are on top of the Snapshot API ones. This may not be ideal since this'll become dependent to the Snapshot PR being merged first. Could the NIC api be isolated from this in a way that it works on top of latest commit?

Also, I noticed that the git tree isn't in sync as well. Instead of doing the long process I [described](https://github.com/devcsrj/jclouds-labs/pull/2#issuecomment-73446569) before, you could also do:
- Copy (only) the _profitbricks_ directory of this version to somewhere.
- Do a `git reset --hard upstream/master` // where upstream is the remote name of jclouds main. Do a `git fetch` if required
- On your explorer, replace the now _synced_ folder with the one backed-up earlier. This way, git treats all of replaced files as _changes to be committed_.
- Commit all changes, with a message=PR title

**Comment by jasmingacic** [comment]
If I was to 
git reset --hard upstream/master // where upstream is the remote name of jclouds main.
replace the now synced folder with copy the profitbricks directory of this version 
Commit all changes

Would this be enough?

**Comment by devcsrj** [comment]
Yep, and you do a force push. You'll see the reflected change on the PR
then right away. :)

**Comment by devcsrj** [comment]
Closing this one to make a new branch containing both NIC and Firewall API.

**Pull request closed without merging**
