### PR TITLE
Snapshot api

### PR DESCRIPTION
**Pull request by baldwinSPC**
Here's the new PR.

### CODE REVIEW

**Comment by devcsrj** [comment]
Hi! Thanks for the PR. Unfortunately, the PR still have merge conflicts. 
I suggest syncing the git tree first. You could rebase your branch first with my version, re-apply the changes you have made, do a force push, then make the PR. If you need assistance feel free to ping me on hangouts/gmail as usual.

Looking forward to resolving this one. :)

**Comment by jasmingacic** [comment]
RJ we've synced our tree to the latest version. So please go ahead and review it.

**Comment by devcsrj** [comment]
Hi @jasmingacic ! I added comments on the codes, and here are other notes:

I tried running the live test on my end, and both the `update` and `rollback` failed. I have one 40GB-storage on my account. I presume that the failure is because, the snapshot created from that storage is still `INPROCESS`, and so calling further operations on that snapshot failed. This is btw the same reason of writing the [ProvisioningStatusPollingPredicate](https://github.com/devcsrj/jclouds-labs/blob/master/profitbricks/src/main/java/org/jclouds/profitbricks/compute/internal/ProvisioningStatusPollingPredicate.java#L32) (e.g.: when provisioning a storage, it has to be in `AVAILABLE` state to successfully connect in a server, and so I intentionally block and wait for it) and doing `@Test(dependsOn = "<other method>")` on my live tests (e.g.: no racing on the value of `storageId`).

On your version as well of `ResponseStatusFromPayloadHttpCommandExecutorService`, do an `Organize Imports` on your IDE. The `mvn clean install` build fails due to unused imports.

**Comment by jasmingacic** [comment]
I found unused imports in this class ResponseStatusFromPayloadHttpCommandExecutorService I removed them.

**Comment by jasmingacic** [comment]
Go ahead and check it out

**Comment by devcsrj** [comment]
Hi @jasminSPC ! On your [SnapshotApiLiveTest#getSnapshotId()](https://github.com/StackPointCloud/jclouds-labs/blob/snapshot-api/profitbricks/src/test/java/org/jclouds/profitbricks/features/SnapshotApiLiveTest.java#L133), you are fetching the first available snapshot (and gets called for every test method). It might be better if the test class is using the newly created snapshot, for all the other test. Could you refactor this?

**Comment by ghost** [comment]
Here
https://github.com/StackPointCloud/jclouds-labs/blob/snapshot-api/profitbricks/src/test/java/org/jclouds/profitbricks/features/SnapshotApiLiveTest.java#L63
you
can see that I'm using snapshotId of a newly created snapshot. In case if
createSnapshot failed I fetch first available snapshotId only if snapshotId
is Null
https://github.com/StackPointCloud/jclouds-labs/blob/snapshot-api/profitbricks/src/test/java/org/jclouds/profitbricks/features/SnapshotApiLiveTest.java#L134,
I do the same
https://github.com/StackPointCloud/jclouds-labs/blob/snapshot-api/profitbricks/src/test/java/org/jclouds/profitbricks/features/SnapshotApiLiveTest.java#L149
in
case storageId is null. So I'm not adding any overhead. This way tests are
fully automated and don't require and user input.

**Comment by devcsrj** [comment]
I understand what you mean. All I'm saying is, if you're using the same ID of the newly created snapshot, on what cases would the `snapshotId` property be null? And if it was, how do we make sure that the first fetched snapshot on the loop is the same created one? 

Also, I still see lines of `System.out`. Could you check the files and make sure they don't contain 'em?

**Comment by jasmingacic** [comment]
Since the tests are not too verbose println are used to show how far the test has progressed. 

As for snapshotId in case the createSnapshot fails it doesn't mean that remaining functions are failing too. The functions don't ensure anything except for taking the first available snapshot to work with.

**Comment by devcsrj** [comment]
Hmmm. Actually, the preference of not using `System.out` is from the jclouds, not mine. ;) They're using an [injected logger](https://github.com/jclouds/jclouds/blob/master/compute/src/main/java/org/jclouds/compute/domain/internal/TemplateBuilderImpl.java#L79).

Yep, that's correct. However, I think it's better if the _only_ snapshot be used in this test is the same one created. Consider this: `create` fails, the `getSnapshotId()` looks for another, and finds one. That _one_ might be a snapshot with size 80GB (in my case), and the tests `updateSnapshot`, `rollbackSnapshot`, and `deleteSnapshot` will use that fetched one. After the test is done, that 80GB snapshot will get updated, rollbacked in a storage (potentially block for quite a while), and be deleted.

I suggest failing everything else if the `createSnapshot` fails. Thoughts?

**Comment by jasmingacic** [comment]
I removed the print lines.

As for the snapshotId, I can assume several scenarios. 
This function getStorage returns INACTIVE or a DELETED storage then everything fails it doesn't make sense. 

I'd leave it for time being and see what jClouds guys say about it. It is no hustle to remove the function if it is redundant.

**Comment by devcsrj** [comment]
Just final thoughts to convince you. `testCreateSnapshot` is the first method executed in the test. If that fails, there's no need to continue and wait for other tests (i.e.: skip) since you don't ship the code with a failed test anyway. 

Alright, if that's the case, I'll close this pull request now. Although final remarks, sync your git tree first (you're still working from `cf514e9`), then squash the changes you've made so far. Afterwards you may send the PR to the labs. 

Thanks for the great work! :)

**Comment by jasmingacic** [comment]
I fetched your master and merged it into my branch. All the latest commits. Am I missing something?

**Comment by jasmingacic** [comment]
This branch is 9 commits ahead of devcsrj:snapshot-api

https://github.com/StackPointCloud/jclouds-labs/tree/master

This branch is 31 commits ahead of devcsrj:snapshot-api

https://github.com/StackPointCloud/jclouds-labs/tree/snapshot-api

**Comment by devcsrj** [comment]
Not exactly missing commits. The base commit your tree is using (`cf514e9`) is the `JCLOUDS-702: JCloud ProfitBricks provider implementation` which is the commit for when that is still on my tree. When the PR got merged, the new commit sha in the labs is [6e1a037](https://github.com/jclouds/jclouds-labs/commit/6e1a0376f837e2dfe765758333e09761ff39b9b4), which then I re-sync with mine [6e1a037](https://github.com/devcsrj/jclouds-labs/commit/6e1a0376f837e2dfe765758333e09761ff39b9b4).

**Comment by jasmingacic** [comment]
I've lost you :)
What exactly do we need to do?

**Comment by devcsrj** [comment]
Here's what I did on my end (`>` is the terminal symbol) :
`> git reset --hard 1b689dc`  # go to a commit wayback before this PR
`> git remote -v` # on my end, here are the tracked branches

<pre>
    origin  git@github.com:devcsrj/jclouds-labs.git (fetch)
    origin  git@github.com:devcsrj/jclouds-labs.git (push)
    spc git@github.com:StackPointCloud/jclouds-labs.git (fetch)
    spc git@github.com:StackPointCloud/jclouds-labs.git (push)
    upstream    git@github.com:jclouds/jclouds-labs.git (fetch)
    upstream    git@github.com:jclouds/jclouds-labs.git (push)
</pre>

`> git pull upstream master` # pull the latest from upstream, to update git tree
`> git fetch spc snapshot-api` # I'm fetching changes on your branch
`> git cherry-pick --quit`
`> git cherry-pick 4e0722d db2dd75 66b3976 0099b08 1cb3bce 56fe4be 68beb95 3c3c0b3 52a14b8 ddb89a6 204ddd5  770cc78 ce53a33 02dd4b0 d4b6087 6f98728 63da9f7 29eda84 6f3953c`  # commit only changes that you made. There'll be conflicts. resolve in your IDE
`> git cherry-pick --continue` # then continue
`> git reset --soft HEAD~19 && git commit --edit -m "JCLOUDS-702: JCloud ProfitBricks provider - Snapshots API"`  # squash commits. `19` is the number of commits you made (double check) 
`> git push -f <repo> <branch>` # finally, force push into your branch.

Wooh that's many. Haha! cc me on the PR you're going to create on the labs. Thanks! :)

**Comment by jasmingacic** [comment]
I'm done with this.

We'll cc you when we do the PR

**Pull request closed without merging**
